import { ScheduleEvent } from "../storage/scheduleTypes";

export const fakeSchedule: ScheduleEvent[] = [
  {
    id: "1",
    title: "The Electric Owls",
    startTime: "2026-09-05T14:00:00",
    endTime: "2026-09-05T15:00:00",
    stage: "Main Stage",
    category: "Rock",
    tags: ["Live", "Headliner"],
    description: "High-energy alternative rock band from Seattle.",
  },
  {
    id: "2",
    title: "Neon Horizons",
    startTime: "2026-09-05T15:30:00",
    endTime: "2026-09-05T16:30:00",
    stage: "Main Stage",
    category: "Pop",
    tags: ["Dance", "Synth"],
    description: "Electro-pop trio bringing neon vibes to the festival.",
  },
  {
    id: "3",
    title: "DJ Midnight Pulse",
    startTime: "2026-09-05T18:00:00",
    endTime: "2026-09-05T19:30:00",
    stage: "Dance Tent",
    category: "EDM",
    tags: ["DJ", "Bass"],
    description: "Deep house and bass drops all night long.",
  },
  {
    id: "4",
    title: "Local Food Showcase",
    startTime: "2026-09-05T12:00:00",
    endTime: "2026-09-05T20:00:00",
    stage: "Food Court",
    category: "Food",
    tags: ["Vendors", "Local"],
    description: "Taste Seattle’s best street food and artisan treats.",
  },
  {
    id: "5",
    title: "Indie Film Spotlight",
    startTime: "2026-09-06T13:00:00",
    endTime: "2026-09-06T14:30:00",
    stage: "Film Lounge",
    category: "Film",
    tags: ["Indie", "Screening"],
    description: "Screening of award-winning independent short films.",
  },
  {
    id: "6",
    title: "The Velvet Pines",
    startTime: "2026-09-06T15:00:00",
    endTime: "2026-09-06T16:00:00",
    stage: "Acoustic Stage",
    category: "Folk",
    tags: ["Acoustic", "Chill"],
    description: "Smooth harmonies and heartfelt lyrics.",
  },
  {
    id: "7",
    title: "Comedy Hour with Jamie Sparks",
    startTime: "2026-09-06T17:00:00",
    endTime: "2026-09-06T18:00:00",
    stage: "Comedy Tent",
    category: "Comedy",
    tags: ["Stand-Up"],
    description: "An hour of laughs and spontaneous crowd work.",
  },
  {
    id: "8",
    title: "Street Art Workshop",
    startTime: "2026-09-06T11:00:00",
    endTime: "2026-09-06T12:30:00",
    stage: "Art Pavilion",
    category: "Workshop",
    tags: ["Interactive", "Creative"],
    description: "Learn graffiti basics from local mural artists.",
  },
];